import { writeFileSync } from 'fs';
import { dialog } from 'electron';

interface ExportData {
  providers: Array<{
    name: string;
    type: string;
    baseUrl?: string;
    apiKey?: string;
    models?: string[];
  }>;
}

// Cherry Studio - exports as JSON config
export async function exportCherryStudio(data: ExportData): Promise<string> {
  const cherryConfig = {
    providers: data.providers.map((p) => ({
      id: p.type,
      name: p.name,
      apiKey: p.apiKey || '',
      apiHost: p.baseUrl || '',
      models: p.models || [],
    })),
  };

  const result = await dialog.showSaveDialog({
    title: 'Export to Cherry Studio',
    defaultPath: 'cherry-studio-config.json',
    filters: [{ name: 'JSON', extensions: ['json'] }],
  });

  if (result.filePath) {
    writeFileSync(result.filePath, JSON.stringify(cherryConfig, null, 2), 'utf-8');
    return result.filePath;
  }
  throw new Error('Export cancelled');
}

// LobeChat - exports as JSON config
export async function exportLobeChat(data: ExportData): Promise<string> {
  const lobeConfig = {
    languageModel: {
      providers: data.providers.map((p) => ({
        id: p.type,
        name: p.name,
        apiKey: p.apiKey || '',
        baseURL: p.baseUrl || '',
        models: p.models || [],
      })),
    },
  };

  const result = await dialog.showSaveDialog({
    title: 'Export to LobeChat',
    defaultPath: 'lobechat-config.json',
    filters: [{ name: 'JSON', extensions: ['json'] }],
  });

  if (result.filePath) {
    writeFileSync(result.filePath, JSON.stringify(lobeConfig, null, 2), 'utf-8');
    return result.filePath;
  }
  throw new Error('Export cancelled');
}

// ChatGPT Next Web - exports as .env file
export async function exportChatGptNextWeb(data: ExportData): Promise<string> {
  const envLines = data.providers
    .filter((p) => p.apiKey)
    .map((p) => {
      const keyUpper = p.type.toUpperCase().replace(/-/g, '_');
      return `OPENAI_API_KEY=${p.apiKey}\nOPENAI_BASE_URL=${p.baseUrl || 'https://api.openai.com'}`;
    })
    .join('\n');

  const envContent = `# ChatGPT Next Web Configuration\n# Generated by LLM Status\n\n${envLines}\n`;

  const result = await dialog.showSaveDialog({
    title: 'Export to ChatGPT Next Web',
    defaultPath: '.env',
    filters: [{ name: 'Environment', extensions: ['env'] }],
  });

  if (result.filePath) {
    writeFileSync(result.filePath, envContent, 'utf-8');
    return result.filePath;
  }
  throw new Error('Export cancelled');
}

// Dify - exports as JSON config
export async function exportDify(data: ExportData): Promise<string> {
  const difyConfig = {
    model_providers: data.providers.map((p) => ({
      provider: p.type,
      name: p.name,
      credentials: {
        openai_api_key: p.apiKey || '',
        openai_api_base: p.baseUrl || '',
      },
    })),
  };

  const result = await dialog.showSaveDialog({
    title: 'Export to Dify',
    defaultPath: 'dify-config.json',
    filters: [{ name: 'JSON', extensions: ['json'] }],
  });

  if (result.filePath) {
    writeFileSync(result.filePath, JSON.stringify(difyConfig, null, 2), 'utf-8');
    return result.filePath;
  }
  throw new Error('Export cancelled');
}

// AnythingLLM - exports as JSON config
export async function exportAnythingLLM(data: ExportData): Promise<string> {
  const anythingConfig = {
    LLMProvider: data.providers[0]?.type || 'openai',
    LLMApiKey: data.providers[0]?.apiKey || '',
    LLMBasePath: data.providers[0]?.baseUrl || '',
  };

  const result = await dialog.showSaveDialog({
    title: 'Export to AnythingLLM',
    defaultPath: 'anythingllm-config.json',
    filters: [{ name: 'JSON', extensions: ['json'] }],
  });

  if (result.filePath) {
    writeFileSync(result.filePath, JSON.stringify(anythingConfig, null, 2), 'utf-8');
    return result.filePath;
  }
  throw new Error('Export cancelled');
}
